<script lang="ts">
	import { onMount } from 'svelte';
	import { location } from '$lib/stores';

	onMount(() => {
		location.set('tokens');
	});
</script>

<div class="w-full p-2 flex flex-col gap-2">
	<div class="w-full flex justify-end">
		<button class="shadow-lg p-2 border w-32 rounded-md">
      <h1>New</h1>
    </button>
	</div>
  <div class="w-full h-full bg-red-400 flex justify-between">
    <h1>Token</h1>
    <h1>Generated by</h1>
    <h1>Actions</h1>
  </div>
</div>
